package com.nexus.GYMPULSE.integration;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.nexus.GYMPULSE.model.equipment.Equipment;
import com.nexus.GYMPULSE.repositories.EquipmentRepository;
import com.nexus.GYMPULSE.requests.EquipmentRequest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.util.Optional;

import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class EquipmentIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private EquipmentRepository equipmentRepository;

    private EquipmentRequest validEquipmentRequest;

    @BeforeEach
    void setUp() {
        equipmentRepository.deleteAll();

        validEquipmentRequest = new EquipmentRequest();
        validEquipmentRequest.setName("Power Rack");
        validEquipmentRequest.setType("Strength");
        validEquipmentRequest.setBrand("Titan Fitness");
        validEquipmentRequest.setQuantity(2);
        validEquipmentRequest.setAvailable(true);
    }

    @AfterEach
    void tearDown() {
        equipmentRepository.deleteAll();
    }

    @Test
    void createEquipment_withValidData_shouldReturnCreated() throws Exception {
        mockMvc.perform(post("/equipment")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validEquipmentRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name", is(validEquipmentRequest.getName())))
                .andExpect(jsonPath("$.brand", is(validEquipmentRequest.getBrand())))
                .andExpect(jsonPath("$.id", notNullValue())); // ID is generated by DB
    }

    @Test
    void createEquipment_withInvalidData_shouldReturnBadRequest() throws Exception {
        EquipmentRequest invalidRequest = new EquipmentRequest();
        invalidRequest.setName(""); // Blank name
        invalidRequest.setBrand(null); // Null brand
        invalidRequest.setQuantity(-5); // Negative quantity

        mockMvc.perform(post("/equipment")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(invalidRequest)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.errors", hasItem("Equipment name cannot be blank")))
                .andExpect(jsonPath("$.errors", hasItem("Equipment brand cannot be blank"))) // @NotBlank handles null
                .andExpect(jsonPath("$.errors", hasItem("Quantity cannot be negative")));
    }

    @Test
    void getEquipmentById_whenEquipmentExists_shouldReturnEquipment() throws Exception {
        Equipment equipment = new Equipment(null, "Barbell", "Strength", "Rogue", 10, true);
        Equipment savedEquipment = equipmentRepository.save(equipment);

        mockMvc.perform(get("/equipment/" + savedEquipment.getId()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name", is("Barbell")))
                .andExpect(jsonPath("$.id", is(savedEquipment.getId())));
    }

    @Test
    void getEquipmentById_whenEquipmentDoesNotExist_shouldReturnNotFound() throws Exception {
        mockMvc.perform(get("/equipment/nonExistentId"))
                .andExpect(status().isNotFound());
    }

    @Test
    void getAllEquipment_shouldReturnListOfEquipment() throws Exception {
        equipmentRepository.save(new Equipment(null, "Kettlebell", "Strength", "Generic", 20, true));
        equipmentRepository.save(new Equipment(null, "Yoga Mat", "Accessory", "Lululemon", 30, true));

        mockMvc.perform(get("/equipment"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(2)))
                .andExpect(jsonPath("$[0].name", is("Kettlebell")))
                .andExpect(jsonPath("$[1].name", is("Yoga Mat")));
    }

    @Test
    void updateEquipment_whenEquipmentExistsAndDataIsValid_shouldReturnOk() throws Exception {
        Equipment existingEquipment = new Equipment(null, "Old Treadmill", "Cardio", "OldBrand", 1, true);
        existingEquipment = equipmentRepository.save(existingEquipment);

        validEquipmentRequest.setName("New Treadmill Pro");

        mockMvc.perform(put("/equipment/" + existingEquipment.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validEquipmentRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name", is("New Treadmill Pro")))
                .andExpect(jsonPath("$.id", is(existingEquipment.getId())));

        Optional<Equipment> updatedInDb = equipmentRepository.findById(existingEquipment.getId());
        assertTrue(updatedInDb.isPresent());
        assertEquals("New Treadmill Pro", updatedInDb.get().getName());
    }

    @Test
    void updateEquipment_whenEquipmentDoesNotExist_shouldReturnNotFound() throws Exception {
        mockMvc.perform(put("/equipment/nonExistentEqId")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validEquipmentRequest)))
                .andExpect(status().isNotFound());
    }

    @Test
    void deleteEquipment_whenEquipmentExists_shouldReturnNoContent() throws Exception {
        Equipment equipmentToDelete = new Equipment(null, "Spin Bike", "Cardio", "Peloton", 1, true);
        equipmentToDelete = equipmentRepository.save(equipmentToDelete);

        mockMvc.perform(delete("/equipment/" + equipmentToDelete.getId()))
                .andExpect(status().isNoContent());

        assertTrue(equipmentRepository.findById(equipmentToDelete.getId()).isEmpty());
    }

    @Test
    void deleteEquipment_whenEquipmentDoesNotExist_shouldReturnNotFound() throws Exception {
        mockMvc.perform(delete("/equipment/nonExistentEqId01"))
                .andExpect(status().isNotFound());
    }
}
