package com.nexus.GYMPULSE.service.implementations;

import java.util.List;
// import java.util.NoSuchElementException; // Replaced with custom exception
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.nexus.GYMPULSE.exception.ResourceNotFoundException; // Import custom exception
import com.nexus.GYMPULSE.model.workoutplan.DailyWorkout;
import com.nexus.GYMPULSE.model.workoutplan.Exercise;
import com.nexus.GYMPULSE.repositories.DailyWorkoutRepository;
import com.nexus.GYMPULSE.requests.DailyWorkoutRequest;
import com.nexus.GYMPULSE.service.interfaces.DailyWorkoutService;
// import com.nexus.GYMPULSE.utils.GymLogger; // Will be removed

@Service
public class DailyWorkoutImpl implements DailyWorkoutService {
    private static final Logger logger = LoggerFactory.getLogger(DailyWorkoutImpl.class); // SLF4J Logger

    @Autowired
    private DailyWorkoutRepository dailyWorkoutRepository;

    @Override
    public DailyWorkout createDailyWorkout(DailyWorkoutRequest dailyWorkoutRequest) { // Changed signature
        // Create a new DailyWorkout and save it to the repository
        // ID for DailyWorkout is usually auto-generated by MongoDB if not set.
        // If dailyWorkoutRequest.getId() is present, it might be used, or a new one generated.
        // For now, assuming ID is auto-generated for new DailyWorkouts.
        DailyWorkout dailyWorkout = new DailyWorkout(
                dailyWorkoutRequest.getDayOfWeek(),
                dailyWorkoutRequest.getExercises()
        );
        // If an ID is provided in the request and needs to be used, set it explicitly:
        // if (dailyWorkoutRequest.getId() != null && !dailyWorkoutRequest.getId().isEmpty()) {
        //    dailyWorkout.setId(dailyWorkoutRequest.getId());
        // }
        DailyWorkout savedDailyWorkout = dailyWorkoutRepository.insert(dailyWorkout);
        logger.info("New DailyWorkout created, Day of Week: {}", savedDailyWorkout.getDayOfWeek()); // SLF4J logging
        return savedDailyWorkout;
    }

    @Override
    public List<DailyWorkout> allDailyWorkouts() {
        // Return all DailyWorkouts from the repository
        return dailyWorkoutRepository.findAll();
    }

    @Override
    public Optional<DailyWorkout> dailyWorkoutByDayOfWeek(String dayOfWeek) {
        // Retrieve a DailyWorkout by the specified day of the week
        return dailyWorkoutRepository.findDailyWorkoutByDayOfWeek(dayOfWeek);
    }

    @Override
    public Optional<DailyWorkout> dailyWorkoutById(String id) {
        // Retrieve a DailyWorkout by its ID
        return dailyWorkoutRepository.findDailyWorkoutById(id);
    }

    // Removed findDailyWorkoutByDayOfWeek as it's redundant with dailyWorkoutByDayOfWeek
    // @Override
    // public Optional<DailyWorkout> findDailyWorkoutByDayOfWeek(String dayOfWeek) {
    //     return Optional.empty();
    // }

    @Override
    public DailyWorkout updateDailyWorkout(String id, DailyWorkoutRequest dailyWorkoutRequest) {
        // Update an existing DailyWorkout
        DailyWorkout dailyWorkout = dailyWorkoutRepository.findDailyWorkoutById(id)
                .orElseThrow(() -> new ResourceNotFoundException("DailyWorkout", "id", id));

        dailyWorkout.setDayOfWeek(dailyWorkoutRequest.getDayOfWeek());
        dailyWorkout.setExercises(dailyWorkoutRequest.getExercises());
        logger.info("DailyWorkout updated, ID: {}", id); // SLF4J logging
        return dailyWorkoutRepository.save(dailyWorkout);
    }

    @Override
    public void deleteDailyWorkout(String id) {
        // Delete a DailyWorkout by its ID
        DailyWorkout dailyWorkout = dailyWorkoutRepository.findDailyWorkoutById(id)
                .orElseThrow(() -> new ResourceNotFoundException("DailyWorkout", "id", id));

        logger.info("DailyWorkout deleted, ID: {}", id); // SLF4J logging
        dailyWorkoutRepository.delete(dailyWorkout);
    }
}
