package com.nexus.GYMPULSE.service.implementations;

import com.nexus.GYMPULSE.exception.ResourceNotFoundException; // Import custom exception
import com.nexus.GYMPULSE.model.equipment.Equipment;
import com.nexus.GYMPULSE.repositories.EquipmentRepository;
import com.nexus.GYMPULSE.requests.EquipmentRequest; // Import EquipmentRequest
import com.nexus.GYMPULSE.service.interfaces.EquipmentService;
import org.slf4j.Logger; // Import SLF4J Logger
import org.slf4j.LoggerFactory; // Import SLF4J LoggerFactory
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class EquipmentServiceImpl implements EquipmentService {

    private static final Logger logger = LoggerFactory.getLogger(EquipmentServiceImpl.class); // SLF4J Logger

    @Autowired
    private EquipmentRepository equipmentRepository;

    @Override
    public Equipment addEquipment(EquipmentRequest equipmentRequest) {
        Equipment equipment = new Equipment();
        // ID is typically generated by MongoDB, so we don't set it from request for new equipment.
        // If equipmentRequest.getId() is populated, it might indicate an attempt to suggest an ID,
        // which might be ignored by MongoDB's default ID generation or could be used if that's the desired behavior.
        // For now, let's assume ID is auto-generated.
        equipment.setName(equipmentRequest.getName());
        equipment.setType(equipmentRequest.getType());
        equipment.setBrand(equipmentRequest.getBrand());
        equipment.setQuantity(equipmentRequest.getQuantity());
        equipment.setAvailable(equipmentRequest.isAvailable());

        Equipment savedEquipment = equipmentRepository.save(equipment);
        logger.info("Equipment added: {}", savedEquipment.getName());
        return savedEquipment;
    }

    @Override
    public List<Equipment> getAllEquipment() {
        logger.info("Retrieving all equipment");
        return equipmentRepository.findAll();
    }

    @Override
    public Optional<Equipment> getEquipmentById(String id) {
        logger.info("Retrieving equipment by ID: {}", id);
        // The controller will handle throwing ResourceNotFoundException if Optional is empty.
        return equipmentRepository.findById(id);
    }

    @Override
    public Equipment updateEquipment(String id, EquipmentRequest equipmentRequest) {
        Equipment equipment = equipmentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Equipment", "id", id));

        equipment.setName(equipmentRequest.getName());
        equipment.setType(equipmentRequest.getType());
        equipment.setBrand(equipmentRequest.getBrand());
        equipment.setQuantity(equipmentRequest.getQuantity());
        equipment.setAvailable(equipmentRequest.isAvailable());
        // equipment.setId(id); // ID is already set and should not change

        Equipment updatedEquipment = equipmentRepository.save(equipment);
        logger.info("Equipment updated: {}", updatedEquipment.getName());
        return updatedEquipment;
    }

    @Override
    public void deleteEquipment(String id) {
        if (!equipmentRepository.existsById(id)) {
            throw new ResourceNotFoundException("Equipment", "id", id);
        }
        equipmentRepository.deleteById(id);
        logger.info("Equipment deleted, ID: {}", id);
    }
}
