package com.nexus.GYMPULSE.service.implementations;

import java.util.List;
// import java.util.NoSuchElementException; // Replaced with custom exception
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.nexus.GYMPULSE.exception.ResourceNotFoundException; // Import custom exception
import com.nexus.GYMPULSE.model.workoutplan.Exercise;
import com.nexus.GYMPULSE.repositories.ExerciseRepository;
import com.nexus.GYMPULSE.requests.ExerciseRequest;
import com.nexus.GYMPULSE.service.interfaces.ExerciseService;
// import com.nexus.GYMPULSE.utils.GymLogger; // Will be removed

@Service
public class ExerciseServiceImpl implements ExerciseService {
    private static final Logger logger = LoggerFactory.getLogger(ExerciseServiceImpl.class); // SLF4J Logger

    @Autowired
    private ExerciseRepository exerciseRepository;

    @Override
    public Exercise createExercise(ExerciseRequest exerciseRequest) { // Changed signature
        // Create a new Exercise and save it to the repository
        Exercise exercise = new Exercise(
                exerciseRequest.getName(),
                exerciseRequest.getQuantitySets(),
                exerciseRequest.getQuantityReps(),
                exerciseRequest.getResTimeSeconds()
        );
        // ID for Exercise is auto-generated by MongoDB.
        Exercise savedExercise = exerciseRepository.insert(exercise);
        logger.info("New Exercise created, Name: {}", savedExercise.getName()); // SLF4J logging
        return savedExercise;
    }

    @Override
    public List<Exercise> allExercises() {
        // Return a list of all Exercises in the repository
        return exerciseRepository.findAll();
    }

    // Removed findExerciseById as it's redundant with exerciseById
    // @Override
    // public Optional<Exercise> findExerciseById(String id) {
    //    return exerciseRepository.findById(id);
    // }

    @Override
    public Optional<Exercise> exerciseById(String id) {
        // Retrieve an Exercise by its ID
        return exerciseRepository.findById(id);
    }

    @Override
    public Exercise updateExercise(String id, ExerciseRequest exerciseRequest) {
        // Update an existing Exercise
        Exercise exercise = exerciseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Exercise", "id", id));

        exercise.setName(exerciseRequest.getName());
        exercise.setQuantityReps(exerciseRequest.getQuantityReps());
        exercise.setQuantitySets(exerciseRequest.getQuantitySets());
        exercise.setResTimeSeconds(exerciseRequest.getResTimeSeconds());
        logger.info("Exercise updated, ID: {}", id); // SLF4J logging
        return exerciseRepository.save(exercise);
    }

    @Override
    public Exercise cloneExercise(String id) {
        // Clone an existing Exercise
        Exercise original = exerciseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Exercise", "id", id));

        Exercise cloned = original.clone(); // Use the clone method to create a copy
        logger.info("Exercise cloned, Original ID: {}, New ID: {}", id, cloned.getId()); // SLF4J logging
        return exerciseRepository.save(cloned); // Save the cloned exercise
    }

    @Override
    public void deleteExerciseById(String id) {
        // Delete an Exercise by its ID
        Exercise exercise = exerciseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Exercise", "id", id));

        logger.info("Exercise deleted, ID: {}", id); // SLF4J logging
        exerciseRepository.delete(exercise);
    }
}
