package com.nexus.GYMPULSE.requests;

import com.nexus.GYMPULSE.model.workoutplan.WorkoutPlan;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;

// Request object for creating or updating a Member
@Data
public class MemberRequest {
    // memberId is usually generated by the system, so not typically validated on input for creation,
    // but could be validated if provided for updates. For now, no validation.
    private String memberId; // Unique identifier for the member

    @NotBlank(message = "Membership type cannot be blank")
    @Size(min = 3, max = 50, message = "Membership type must be between 3 and 50 characters")
    private String memberShipType; // Type of membership (e.g., basic, premium)

    @NotBlank(message = "Start date cannot be blank")
    @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$", message = "Start date must be in YYYY-MM-DD format")
    private String startDate; // Membership start date

    @NotBlank(message = "End date cannot be blank")
    @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$", message = "End date must be in YYYY-MM-DD format")
    private String endDate; // Membership end date

    // Assuming WorkoutPlan object itself is validated elsewhere or its fields are.
    // If WorkoutPlan is complex and needs validation, @Valid annotation might be needed here.
    private WorkoutPlan workoutPlan; // Workout plan associated with the member

    @NotBlank(message = "Full name cannot be blank")
    @Size(min = 2, max = 100, message = "Full name must be between 2 and 100 characters")
    private String fullName; // Full name of the member

    @NotBlank(message = "Email cannot be blank")
    @Email(message = "Email should be valid")
    private String email; // Email address of the member

    @NotBlank(message = "Address cannot be blank")
    @Size(min = 5, max = 200, message = "Address must be between 5 and 200 characters")
    private String address; // Residential address of the member

    @NotBlank(message = "Phone number cannot be blank")
    @Pattern(regexp = "^\\+?[0-9. ()-]{7,25}$", message = "Phone number is not valid")
    private String phoneNumber; // Contact phone number of the member
}
