package com.nexus.GYMPULSE.requests;

import jakarta.validation.constraints.*;
import lombok.Data;

// Request object for creating or updating a Trainer
@Data
public class TrainerRequest {

    @NotBlank(message = "Full name cannot be blank")
    @Size(min = 2, max = 100, message = "Full name must be between 2 and 100 characters")
    private String fullName; // Full name of the trainer

    @NotBlank(message = "Email cannot be blank")
    @Email(message = "Email should be valid")
    private String email; // Email address of the trainer

    @NotBlank(message = "Phone number cannot be blank")
    @Pattern(regexp = "^\\+?[0-9. ()-]{7,25}$", message = "Phone number is not valid")
    private String phoneNumber; // Contact phone number of the trainer

    @NotBlank(message = "Address cannot be blank")
    @Size(min = 5, max = 200, message = "Address must be between 5 and 200 characters")
    private String address; // Residential address of the trainer

    // trainerId is usually generated by the system for creation.
    // No validation here, but could be validated if part of an update path explicitly.
    private String trainerId; // Unique identifier for the trainer

    @NotBlank(message = "Speciality cannot be blank")
    @Size(min = 3, max = 100, message = "Speciality must be between 3 and 100 characters")
    private String speciality; // Area of expertise (e.g., strength training, yoga)

    @NotNull(message = "Salary cannot be null")
    @Positive(message = "Salary must be a positive value")
    private Double salary; // Salary of the trainer

    @NotBlank(message = "Certification number cannot be blank")
    @Size(min = 3, max = 50, message = "Certification number must be between 3 and 50 characters")
    private String certificationNumber; // Trainer's certification number
}
